#:schema node_modules/wrangler/config-schema.json
name = "durable-presentation-server"
main = "src/index.ts"
compatibility_date = "2024-09-03"

[placement]
mode = "smart"

[[durable_objects.bindings]]
name = "WEBSOCKET_HIBERNATION_SERVER"
class_name = "WebSocketHibernationServer"

[[migrations]]
tag = "v1"
new_classes = ["WebSocketHibernationServer"]