name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types:
      - completed

jobs:
  deploy-server:
    name: Deploy Worker
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
        contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Bump npm version
      id: versioning
      uses: phips28/gh-action-bump-version@master
      with:
        tag-prefix: 'v'
        patch-wording: 'bump-patch,fixes,Fixes,bugfix,Bugfix,patch,hotfix,Hotfix'
        minor-wording: 'bump-minor,adds,Adds,new'
        major-wording: 'bump-major,MAJOR,removes,Removes,delete,Delete'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PACKAGEJSON_DIR: 'durable-presentation-next'

    - name: Update version in durable-presentation-server
      run: |
        VERSION=$(jq -r '.version' durable-presentation-next/package.json)
        jq ".version = \"$VERSION\"" durable-presentation-server/package.json > durable-presentation-server/package.json.tmp && mv durable-presentation-server/package.json.tmp durable-presentation-server/package.json
        cat durable-presentation-server/package.json | jq '.version'

    - name: Deploy
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        workingDirectory: ./durable-presentation-server